// Generated by IcedCoffeeScript 1.8.0-d
(function() {
  define(function() {
    var shapeRightBox;
    return shapeRightBox = (function() {
      function shapeRightBox(container, selector) {
        var $shapeRightBox, shapeResizeHandler;
        $shapeRightBox = container.find(selector);
        shapeResizeHandler = function() {
          var $shapeBoxRightParent, $shapeBoxRightParentHeight, shapeBottomBound, shapeTopBound;
          $shapeBoxRightParent = $shapeRightBox.parent();
          $shapeBoxRightParentHeight = $shapeBoxRightParent.height();
          shapeTopBound = $shapeBoxRightParentHeight - 450 + 15;
          shapeBottomBound = $shapeBoxRightParentHeight + 15;
          return $shapeRightBox.css({
            "-webkit-shape-outside": "polygon(600px " + shapeTopBound + "px, 600px " + shapeBottomBound + "px, 200px " + shapeBottomBound + "px)"
          });
        };
        $(window).on("resize", function(event) {
          event.stopPropagation();
          return shapeResizeHandler(event);
        });
        setTimeout(function() {
          return shapeResizeHandler();
        });
      }

      return shapeRightBox;

    })();
  });

}).call(this);
