// Generated by CoffeeScript 1.8.0
(function() {
  require.config({
    paths: {
      text: "libs/text"
    }
  });

  require(["app"]);

  $.prototype.cloneElement = function($element) {
    return $(this[0].cloneNode());
  };

  _.templateSettings.interpolate = /\{(.+?)\}/g;

}).call(this);
