// Generated by CoffeeScript 1.8.0
(function() {
  define(["text!component/field/mobile.html", "component/field/model", "plugin/phone.mask", "text!cache/phone.mask.json", "component/field/animate.error"], function(template, FieldModel, PhoneMask, phoneMask, AnimateError) {
    return Backbone.View.extend({
      model: new FieldModel,
      events: {
        "input input": function(event) {
          this.animateError.hideAnimate(".empty");
          return this.model.set({
            result: this.phoneMask(event)
          });
        }
      },
      getValue: function() {
        var result;
        result = this.model.get("result");
        if (result) {
          return result;
        } else {
          return this.animateError.showAnimate(".empty") && void 0;
        }
      },
      initialize: function() {
        var $template;
        $template = $(template);
        this.$el.append($template);
        this.animateError = new AnimateError($template, [".empty"]);
        return this.phoneMask = new PhoneMask(JSON.parse(phoneMask));
      }
    });
  });

}).call(this);
