// Generated by IcedCoffeeScript 1.8.0-d
(function() {
  define(["text!./template.html", "global/shapeRightPanelBox"], function(template, ShapeRightPanelBox) {
    var View;
    return View = Backbone.View.extend({
      className: "view-one",
      initialize: function() {
        this.$el.html(template);
        return new ShapeRightPanelBox(this.$el, ".shape-right-box");
      }
    });
  });

}).call(this);
