// Generated by IcedCoffeeScript 1.8.0-d
(function() {
  define(["text!./template.html", "global/shapeRightPanelBox"], function(template, ShapeRightPanelBox) {
    var User, View;
    User = Backbone.Model.extend({
      name: ""
    });
    return View = Backbone.View.extend({
      className: "view-one",
      model: new User,
      render: function(user) {
        return this.$user.text(_.template(this.$user.text())({
          user: user
        }));
      },
      initialize: function() {
        this.$el.html(template);
        this.$user = this.$el.find(".user");
        return new ShapeRightPanelBox(this.$el, ".shape-right-box");
      }
    });
  });

}).call(this);
